### ISSUE TITLE
How can we use this?

### ISSUE THREAD

**Issue by cniweb** [jenkinsci/sqlserver-api-plugin#1]
### Describe your use-case which is not covered by existing documentation.

We have a shared library and we would use your plugin.

Our code:
```
import groovy.sql.Sql
import com.microsoft.sqlserver.jdbc.SQLServerDriver;
import com.microsoft.sqlserver.jdbc.SQLServerException;

node() {

  withCredentials([
    string(credentialsId: 'sqluser', variable: 'sqluser'),
    string(credentialsId: 'sqlpass', variable: 'sqlpass')
  ]){
      dbserver = $/SQLSERVER\MSSQLINSTANZ/$
      dbname='SQLDBname'
      def sql = Sql.newInstance("jdbc:sqlserver://$dbserver;databaseName=$dbname;user=$sqluser;password=$sqlpass")
      def sqlresult = sql.execute "SELECT * FROM TABLE"
      println sqlresult
    }
}
```

**Comment by cniweb** [comment]
Error Message:

```
30.11.2022 11:10:06  java.sql.SQLException: No suitable driver found for jdbc:sqlserver://SQLSERVER/MSSQLINSTANZ;databaseName=SQLDBname;user=***;password=***
30.11.2022 11:10:06  	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:702)
30.11.2022 11:10:06  	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
30.11.2022 11:10:06  	at groovy.sql.Sql.newInstance(Sql.java:299)
30.11.2022 11:10:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
30.11.2022 11:10:06  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
30.11.2022 11:10:06  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
30.11.2022 11:10:06  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
30.11.2022 11:10:06  	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
30.11.2022 11:10:06  	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
30.11.2022 11:10:06  	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrap.invoke(StaticMetaMethodSite.java:133)
30.11.2022 11:10:06  	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:102)
30.11.2022 11:10:06  	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)
30.11.2022 11:10:06  	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:197)
30.11.2022 11:10:06  	at org.kohsuke.groovy.sandbox.impl.Checker$2.call(Checker.java:216)
30.11.2022 11:10:06  	at org.kohsuke.groovy.sandbox.GroovyInterceptor.onStaticCall(GroovyInterceptor.java:35)
30.11.2022 11:10:06  	at org.jenkinsci.plugins.scriptsecurity.sandbox.groovy.SandboxInterceptor.onStaticCall(SandboxInterceptor.java:190)
30.11.2022 11:10:06  	at org.kohsuke.groovy.sandbox.impl.Checker$2.call(Checker.java:214)
30.11.2022 11:10:06  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedStaticCall(Checker.java:218)
30.11.2022 11:10:06  	at org.kohsuke.groovy.sandbox.impl.Checker.checkedCall(Checker.java:120)
30.11.2022 11:10:06  	at com.cloudbees.groovy.cps.sandbox.SandboxInvoker.methodCall(SandboxInvoker.java:17)
30.11.2022 11:10:06  	at WorkflowScript.run(WorkflowScript:14)
```
